### ISSUE TITLE
URL для уведомлений

### ISSUE THREAD

**Issue by EGO7000** [mnoskov/commerce-payment-yandexkassa#1]
Доброго времени суток!

Правильно ли я понял, что если указать в настройках Я.Кассы следующий URL для уведомлений:
**https://<адрес сайта>/commerce/yandexkassa/payment-process**
то будет обработан только статус **waiting_for_capture**, судя по коду функции **handleCallback()**?
Или обрабатываются все callback-уведомления от Я.Кассы?

Благодарю за модуль Сommerce и за будущий ответ!
Спасибо.

**Comment by mnoskov** [comment]
Да, обрабатывается только статус waiting_for_capture

**Comment by EGO7000** [comment]
Почитал доку Яндекс.Кассы, там пишут что "waiting_for_capture" используется при [двухстадийных платежах](https://kassa.yandex.ru/developers/payments/payment-process#capture-and-cancel), которые делаются с параметром **capture=false**, т.е. по коду получается, что зачисление платежа не обработается, т.к. в getPaymentLink() 62 строка  **'capture' => true**.
Собственно, сейчас делаю исправления под себя, позже сделаю пул-реквест, а здесь пишу, чтобы если что - людям было понимание куда копать :)
Для платежей в одну стадию (когда всё автоматом), нужно делать проверку в YandexkassaPayment.php не на "waiting_for_capture", а на **$payment['status'] == 'succeeded'** и закомментить дальнейший `$this->request('payments/' . $payment['id'] . '/capture', [
                  'amount' => $payment['amount'],
              ]);`
т.к. он нужен при всё тех же двухстадийных платежах, а иначе выдаёт на стороне Яндекс.Кассы не критичную ошибку **"Autocapture is enabled for this payment, you don't need to capture it manually."**

**Comment by EGO7000** [comment]
Сделал пулл #3, теперь должно полноценно работать.
